### ISSUE TITLE
Propose Logo

### ISSUE THREAD

**Issue by mirzazulfan** [tovic/text-editor#9]
Hi @tovic . I'am graphic disigner. I want to contribute to this project and I have a new logo design for you, if you allowed I will send to you.

**Comment by tovic** [comment]
Yes of course. Thanks by the way.

**Comment by mirzazulfan** [comment]
Hello sir, If you like it, you can use it. I'll send you files. if you need anything change, i'll fix it, 
![text editor](https://user-images.githubusercontent.com/36124339/39853342-f827b2bc-544b-11e8-9847-81d28a8263ed.png)
Best regard sir, @tovic

**Comment by tovic** [comment]
If you have some experience with SVG, converting them into vector would be better as it is eaay to change the color simply by configuring the `fill` value. But the blue one is good, thanks.

I&rsquo;ll put your name/user in the README then.

**Comment by mirzazulfan** [comment]
I'm glad to hear it sir, you can download all files (SVG, PDF, PNG, CDR) Logotype and editables files here [GDrive](https://drive.google.com/drive/folders/1czeiYoJmJviNyb-8SiTDnER4oxnXWBDK)
i've created a PR #10 please check. 

Thank sir @tovic .

**Comment by tovic** [comment]
I have downloaded it, and will add your pull request after I pushed [some of these plans](https://github.com/tovic/text-editor/issues/8). It may take some time because I am still actively working on the _Mecha_ project for now.

**Comment by mirzazulfan** [comment]
I see,,, Good Luck sir.
